### ISSUE TITLE
Pull in fixes from ledgr/powerdns_exporter and provide up to date Docker image

### ISSUE THREAD

**Issue by bracki** [janeczku/powerdns_exporter#7]
We would love to use the fixed version from https://github.com/ledgr/powerdns_exporter.
Unfortunately the Docker image provided [here](https://hub.docker.com/r/janeczku/powerdns-exporter/) doesn't contain these changes.
The official [Prometheus docs](https://prometheus.io/docs/instrumenting/exporters/#miscellaneous) mention the forked version by @ledgr. What's the case here?

**Comment by ledgr** [comment]
@bracki I am not golang developer and made these changes as a quick fix for our infrastructure after going through golang basics, and I doubt I will get more serious on learning golang in the near future. That's why I can not guarantee I will actively maintain this exporter.

There is a pull request here that hopefully fixes the failing tests (I will check it later): https://github.com/ledgr/powerdns_exporter/pull/6

But even without this PR my fix is in production for quite a long time and it works as expected.

**Comment by ledgr** [comment]
@bracki could you close this issue? It is stale for too long already :)
